//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://johnwalsh.com", ClrNamespace="johnwalsh.com")]

namespace johnwalsh.com
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WeatherInfo", Namespace="http://johnwalsh.com")]
    public partial class WeatherInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private float TemperatureField;
        
        private string cityField;
        
        private JohnsRestWeatherService.DataContracts.WeatherDescription weatherField;
        
        private johnwalsh.com.WindInfo windInfoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Temperature
        {
            get
            {
                return this.TemperatureField;
            }
            set
            {
                this.TemperatureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JohnsRestWeatherService.DataContracts.WeatherDescription weather
        {
            get
            {
                return this.weatherField;
            }
            set
            {
                this.weatherField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public johnwalsh.com.WindInfo windInfo
        {
            get
            {
                return this.windInfoField;
            }
            set
            {
                this.windInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WindInfo", Namespace="http://johnwalsh.com")]
    public partial class WindInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private float AvgWindSpeed_KMField;
        
        private float windSpeed_KMField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float AvgWindSpeed_KM
        {
            get
            {
                return this.AvgWindSpeed_KMField;
            }
            set
            {
                this.AvgWindSpeed_KMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float windSpeed_KM
        {
            get
            {
                return this.windSpeed_KMField;
            }
            set
            {
                this.windSpeed_KMField = value;
            }
        }
    }
}
namespace JohnsRestWeatherService.DataContracts
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WeatherDescription", Namespace="http://schemas.datacontract.org/2004/07/JohnsRestWeatherService.DataContracts")]
    public enum WeatherDescription : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sunny = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rain = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cloudy = 2,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://johnwalsh.com", ConfigurationName="IRestWeatherService")]
public interface IRestWeatherService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://johnwalsh.com/IRestWeatherService/GetWeather", ReplyAction="http://johnwalsh.com/IRestWeatherService/GetWeatherResponse")]
    johnwalsh.com.WeatherInfo GetWeather(string city);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://johnwalsh.com/IRestWeatherService/UpdateWeather", ReplyAction="http://johnwalsh.com/IRestWeatherService/UpdateWeatherResponse")]
    string UpdateWeather(johnwalsh.com.WeatherInfo info);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRestWeatherServiceChannel : IRestWeatherService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RestWeatherServiceClient : System.ServiceModel.ClientBase<IRestWeatherService>, IRestWeatherService
{
    
    public RestWeatherServiceClient()
    {
    }
    
    public RestWeatherServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RestWeatherServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RestWeatherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RestWeatherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public johnwalsh.com.WeatherInfo GetWeather(string city)
    {
        return base.Channel.GetWeather(city);
    }
    
    public string UpdateWeather(johnwalsh.com.WeatherInfo info)
    {
        return base.Channel.UpdateWeather(info);
    }
}
